name: riverpod_practice_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  flutter_hooks: ^0.18.3
  flutter_slidable: ^1.2.0
  hooks_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
